### ISSUE TITLE
Consider marking INFO —  STDERR logs as errors

### ISSUE THREAD

**Issue by egorklepikov** [annikovk/IntelliJ-Log-Analyzer#20]
Example:

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/34603633/177987547-2cc7f4ff-5940-4a2a-9b23-96dae48c01f2.png">

```
08 Jul 2022 11:00:14,010 INFO —  STDERR — java.lang.ClassNotFoundException: MyProxy
08 Jul 2022 11:00:14,010 INFO —  STDERR — 	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:209)
08 Jul 2022 11:00:14,010 INFO —  STDERR — 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
08 Jul 2022 11:00:14,010 INFO —  STDERR — 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
08 Jul 2022 11:00:14,011 INFO —  STDERR — 	at java.base/java.lang.Class.forName0(Native Method)
08 Jul 2022 11:00:14,011 INFO —  STDERR — 	at java.base/java.lang.Class.forName(Class.java:467)
```

**Comment by annikovk** [comment]
Now should represent STDERR exceptions like that: 

![image](https://user-images.githubusercontent.com/12910542/178152829-09fb9287-04d2-4de0-866c-fdcecd412184.png)
![image](https://user-images.githubusercontent.com/12910542/178153243-1f2c76b1-908e-4509-928c-9b37bd286327.png)
